fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"
else_if_brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_single_line = false
fn_args_layout = "Block"
report_todo = "Always"
report_fixme = "Always"
reorder_imports = true
reorder_imported_names = true
